language: android
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-support
  - extra-android-m2repository
before_install:
- openssl aes-256-cbc -K $encrypted_b49aa8624bb6_key -iv $encrypted_b49aa8624bb6_iv -in selfreport/release-key.keystore.enc -out selfreport/release-key.keystore -d
- git clone https://github.com/MD2Korg/mCerebrum-Utilities.git /home/travis/build/MD2Korg/mCerebrum-Utilities
- git clone https://github.com/MD2Korg/mCerebrum-DataKitAPI.git /home/travis/build/MD2Korg/mCerebrum-DataKitAPI
script:
- "./gradlew assembleRelease"
notifications:
  slack:
    secure: drSaLEsi+xlUePocfcDTLO9S/5XSBsnR6h7OzPhU4xsO+mBjH3qb93Qe4Jwzz9IZQ0UFzDcmu7ObHOksd6fDgvnIcmznowuABs7QFSF5dodF3eXuF/NJc5J3SqptrOZhlPhGQJcan8siBpLw5z+UBal9ORQPJ8e0SN2bxvRH30GzOlaBOrS0w9hGmtoIY/c8ZIjxGn7BK+b7qL6pNqD4tTg3BImh4Q8Q0icjlT/Pe4kq9pJuYP+Ph4B6THE5PY6W5kmaPSZT2wk72tbNa+1f0lxkO106+Fi4X/qEf6BNQ/2ufUi8cGyjYhu8ZRfGEQVwmwtk0goZvPRyxzHx94tc0/utmW+ZvEEdXOTfs1cE84xGvsYOmoMaMacJC0DPSRTJ269LnmUlTYZoZPyEaqEJp0vFLnS7ZwYcYBzEQ/coS1zKOEWX5a29ijvCOxeFGWF9NcEvaGfpoP/RiLJXjguKfrQLQiek+xkzmubSRWpP9LFoqtXwVMxle/zi/99Ry02nvmEUSK3BbAM57LBnrT+0lYDC/ocxTpQ3Gvd52qFoZBzb8Fshu2+3UYCSCHROkOdHtBmBvRKE4LiTz8/6xtzeL1n+1RSrbN13tbk01gkNIHagSLWUildtFkvok2pJXawslE88ZhRzOOK8ViWFenbhca6sPfvBebXccTJKnzi4GQc=
    on_success: change
    on_failure: always
    on_start: false
deploy:
  file_glob: true
  provider: releases
  api_key:
    secure: U65Oy/AmZZFdQjnniZKCUSh4Z5Xg3kJj05Dsv6s8CqwrVdbJ2jVOxg3QIpvn4HH+FK/7tgtv+uc1Aa3oL8ZtdIbO+Dmg1dR8VCnlH90PXVi7LJoTcp4bN0UwhcD81F87QjHL3xKPkUiFt/6Soz3FqndW3oh2VCK70xYTeCjUBvoZugzXMTKiel8IZ6hX46rypT+QNWWK34pBXkUOXTidJGyKYFcklSfxYkcfgspmTWOW3vpbgA6nMrZsg9B+n9SyYniVcAa6b2M0Gx/N6YYiTOskd2fLiKCTiB9vwS8rWX7QavwkzkTBniCjfoRrhXISglAutfLkMZ1Y2o9MVWefN7UMMuIQYz4gCREwElO+r+NtuZwA7e6pFJ5pbN8aPkM1w3wKEOb8XK/SwN3++Dcl/aWeDe/Txr+rQ/vXO9+3wqw+8F8b2gjBDGI3w8QDrKj0E9CDxapPRKg1cfhSQvdjgItNE4460cuLQIUYPNrAJQ5ZABREWkVwg01cA/PDZDHkCfjJrOvojvUlecVLfDH/hksOTBEHpr0Y1O1x0Pi1DMNbysFU94ytYFwuB/toSlV3b4MXyT0tGz4XEMr1pfmv4BtinYLI7TuiEceXzr5rh480mm1K2G9/1tmBRVfmrSnIL8BaqbB2E64kAyVIzSnR6YUJDqTb1Ib2Adhrip9p9PY=
  file: selfreport/build/outputs/apk/selfreport*.*.*.apk
  on:
    repo: MD2Korg/mCerebrum-SelfReport
    tags: true
  skip_cleanup: true
env:
  global:
  - secure: UaOo7LycYVQtGZRWPXbBBddA5pJmwzEfmccRTOb2DYnTotpKiJ7mClTIP5DqO656LrtxgE51MXH9tMF6cHp2vtvop5GmY30DO/hMJKFqXwfWcqmKF+qN5lvDQSD/1QlI9mOA2XGJpzudHl2jbXggd99lFPfFu+olq+m6fMxJqtNZwAQB/yt3vAOFhqyQ1bmkP0wt0N/RNkYJWB7oMB4YrXpq2r2S/YIFX12J4Bn613+Z7gOdOfhZxTRnnAkpHuBkkx0Gd+MQXV+ohh3DLDL/DrGJyE4mxJzC38CJ5SNmaIoVXGb1ww4QZJr3x593jKSpJorf2Api3aHKi1ovz0gM8VDwkbstXiv7lIBYlPUltq0LgVMIF0dfTrtnnpwBzyymC9EwyiIcpfne+1Tdf191goSwWQHGtvdknKZ+wTheymydzTtm5WB6/GRe02mA6HmtB4YFfpsHsX+d0VeaFvCCRXqzxvANCrZ2czdvDv3DCeWeFy1HTDZr87R9KWEkv0ie/A9QtJoentRuIb/pStcBkD64AU1LND/u4oiHT1wR259G705z4h7XcpBuIXH+Dp4fN2cwXT3mEClqAphvGZ4IM0NJw0iLe4Qgc73aHgEQ98JWcVQjsRdU2Xh6q1fMSCK6UKbax8ZGHNRo+qlQqp2U/EP7hOLMnbWZnS0ozEWPCg0=
  - secure: pQO7IoNQ1QdHIaAZ0D8jCDCKzb7nQI1XpqMyKwkSR/iPnMSUtAmot+cQI3IHwe31tIC+n3GzxG9QtkjImU5oiR1dyjthce62ybWae12xWqm4OS66jl3hdbsgxXaOUI9tCWPcBZJmSdNShlmuNNfMjFHTZVZ5BrO6nAtnzNReQL5w+5HYo4KLbuH738IeUlt4y0XXOPxAQqK6zwy6jTZHnAYbOASAuOC4OAYtRp+4p5h7qOvGP8x4mpJ0/4QWQznIXFLN5NBxfQEKp8AZLvBQkr5FCqc5+MV26HXJlUIIjueU9l+KjCyWzSqMNfbDR6XWyrT9myT7WHt3+Yb76Y8u98yPYAzIyrahwnbTP4PaKtVJY27vC7jHlLdU2g3WUSn/JzIf6m480bfGYf0opfa4Q7E0uWT8TvkGjZcy2VwHGlkrqr0sbLUwsCqUESRXCFuL+s7OftfQtRZ87mW5b9ScAGT5rrjYgAUAdDFFZVszsp+RGyBsC6UG4RJlZvK2V5YKnX/ne16ibQ3Y7chwUwO/HzqRJGOL6Qp6nZQhP9nwYykYrICc57r4mIn8sewkLDmYNE/1eptu+I+zwiNHYyhvFX6P2uEl7JwVZSfrGjBfT3mywwPU3yWjHk8j9SITAGzxRNvIIPe9yJgvqwHx+9zSXrb5jYfizlno7ymjT7lAzp8=
  - secure: njWbNtSXcJyOrg2Aua+A+bwrdwwi9NnJZcTDonGvpHT60oFTnvUbn+s7k7ugPf+3iP1tQyeOmqXPMV0xccZh9wl3CEHy01wJ84dNAqvoHvNDRPbgNSdjRb4liB60Ib6jZemYb3t1WM+SEuxMQjrvrRbxarzx4v4nccr+5PUccLNvyHPEPN3OHn/x237c7ycWEjpGRjXh7dh3TaghnG6f9J6Vb3fwrmkPITtWcCmsKD9F63fnnqRvmrPG8U4qjNIjjiWwWEIf724zWxMBxE3P8NrxJ9HQjsdQtGpQvkVFz2C69E5fKE4z7rGf5CBCKMFA7Fs3t780vwA5klOk/1wnzv310yc0NH9NoBaOmOCpJQc3KFzNsFhMmApR7OAeEXvQ2cj9qWGlj9vYb1m1eH1ZWz89SIWkB13moKZStcYbaVQdX1qBXunF2CnNO6D0oZCgOyno+8o81eW8w/x2e30HpAwY8ySQuyR5z1dSw2aNmGgrx2uLbyjg1nRJp2DLe4H0mt8egDP3bJQgmwwF40bULt69Mo55snc5EMxOHncR1S2HinUlDYSWwo2/slrgXNYc3hzFxaFfwwx1NEoMpWmCcgbjo5JRBxtmPp50GEgcok28IhCiURSy0zuCiDw1GPP3v181uqkvq+f3iEgkq7Y95NvAY4PoFHbtRbvL2fFW6u4=
  - secure: hgNyMFFBQpOPOOTaSy9WHf2f6meHsYIW1SuHfQw9qKTftnlEv+7bhvZGbH61AU6iYgf3LIwrZkyPH964ZopSHDgyIAeeXwS1e+6zZJOf8Yi8d3rfDDrgXt4gyuz6CJFH2bxZLJ375FU5E0cN3DennD82cMPnOP2cszZKpsNDg/EaYDPdEChboAIBUW1eb2e99H7Ts/8J4027hvnOCkq0OGA7KnaR+N7WdTdMy+/xiVOC9QXQuvjQEKg4a7fTUZqz0qmr9lAc2Y3Hlpzo81+HCZDtySihLyHsdqx1eNASoeEVsn8K/8zbpN77UMn0uR4SdHp6N64Vx6Q26FmgW/jAKowhl2ARD+gvo/zVgDX5x9migpqXTyEmJuyZR6jgF2b9CJYfwLCeIch/Vpcds0RXdUTDrP9QlTQoCoWmJQlZtrlOQM42HjYQ/oBlxiyX91v9aSqE07LbDQdCeXQ1G5BCE1Uo8kULbWrRELil4OoCL2tbdoGZRpkunI6cU7kLxC3bbFO3rtwoHUB61aLWNg/JSLJ+Zn4DijlFY3tNXI05F0l1o6LHdy5vL+hw3dnyJIyRu56gn0lhmaubxt8/9YCuegh5gnxvTWbkhRXH2lAWarsrZXDAXNm0Q/Js53cKHZdGna53muCAJ8dqJCwl9RSV9eptV8Z6b4dQOSGEP8A3GUA=
